### PR TITLE
fix: mariaDB key guessing in financial example

### LINKED ISSUE #1168: bug or expected?
``` r
library(RMariaDB)

my_db <- dbConnect(
  MariaDB(),
  username = "guest",
  password = "relational",
  dbname = "Financial_ijs",
  host = "relational.fit.cvut.cz"
)

library(dm)
#> 
#> Attachement du package : 'dm'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter

my_dm <- dm_from_con(my_db)
#> Keys could not be queried: valeur manquante là où TRUE / FALSE est requis. Use
#> `learn_keys = FALSE` to mute this message.
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by maelle**
Fix #1168

The branch name says it all. :sweat_smile: 

I'll add a test, leaving this as draft while I add it. (tested interactively)

``` r
library(RMariaDB)

my_db <- dbConnect(
  MariaDB(),
  username = "guest",
  password = "relational",
  dbname = "Financial_ijs",
  host = "relational.fit.cvut.cz"
)
library("dm")
#> 
#> Attachement du package : 'dm'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
my_dm <- dm_from_con(my_db)
#> Keys queried successfully, use `learn_keys = TRUE` to mute this message.
```

<sup>Created on 2022-06-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by maelle** [comment]
Happy to learn how and where to test things correctly around here. :slightly_smiling_face:

File: tests/testthat/test-learn.R [hunk 1]
```diff
@@ -470,3 +470,17 @@ test_that("dm_meta() contents", {
...
+test_that("dm_from_con() with mariaDB", {
+  skip_if_offline()
+  my_db <- RMariaDB::dbConnect(
+    RMariaDB::MariaDB(),
+    username = "guest",
+    password = "relational",
+    dbname = "Financial_ijs",
+    host = "relational.fit.cvut.cz"
+  )
+  expect_snapshot_output(my_dm <- dm_from_con(my_db))
```
Comment (krlmlr) [inline tests/testthat/test-learn.R:483]: This produces no output, but we can tackle it later.

**Review by krlmlr — APPROVED** [review]
Thanks!
